import { NextHead } from "../src/utils/NextHead";
import BestMarkets from "../src/components/best/BestMarkets";

export default function Home() {
  return (
    <>
      <NextHead descrpition="Generated by safe-pet" />
      <BestMarkets />
    </>
  );
}
